import { redirect } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { formatRelativeTime, formatDuration } from '@/lib/utils/format'

export const metadata = { title: 'Audio Jobs — Admin' }

export default async function AdminAudioJobsPage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string }>
}) {
  const { status } = await searchParams
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth/sign-in')

  let query = supabase
    .from('lesson_audio')
    .select(`
      *,
      lessons(id, title, courses(title))
    `)
    .order('created_at', { ascending: false })
    .limit(50)

  if (status) query = query.eq('status', status)

  const { data: audioJobs } = await query

  // Count by status
  const { data: counts } = await supabase
    .from('lesson_audio')
    .select('status')

  const statusCounts = (counts || []).reduce((acc: Record<string, number>, r) => {
    acc[r.status] = (acc[r.status] || 0) + 1
    return acc
  }, {})

  const statusColors: Record<string, string> = {
    ready: 'bg-green-100 text-green-700',
    processing: 'bg-blue-100 text-blue-700',
    pending: 'bg-amber-100 text-amber-700',
    failed: 'bg-red-100 text-red-700',
  }

  const providerLabels: Record<string, string> = {
    kokoro: 'Kokoro-82M',
    piper: 'Piper TTS',
    xtts: 'XTTS-v2',
    human_upload: 'Human upload',
    other: 'Other',
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-display font-bold text-navy-500">Audio jobs</h1>
        <p className="text-muted-foreground text-sm mt-0.5">
          TTS audio generation status for lesson read-along audio.
          Phase 2 feature — Kokoro-82M pipeline connects here.
        </p>
      </div>

      {/* Status summary */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {['ready', 'pending', 'processing', 'failed'].map(s => (
          <Link
            key={s}
            href={s === (status || '') ? '/admin/audio-jobs' : `/admin/audio-jobs?status=${s}`}
            className={`et-card p-4 text-center hover:shadow-et-card-hover transition-shadow ${status === s ? 'ring-2 ring-blue-600' : ''}`}
          >
            <div className="font-display text-2xl font-bold text-navy-500">{statusCounts[s] || 0}</div>
            <div className={`badge-pill mt-1.5 ${statusColors[s]}`}>{s}</div>
          </Link>
        ))}
      </div>

      {/* Phase 2 notice */}
      <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-4">
        <div className="flex items-start gap-3">
          <span className="text-xl">🔊</span>
          <div>
            <p className="text-sm font-semibold text-blue-900 mb-1">TTS pipeline (Phase 2)</p>
            <p className="text-xs text-blue-800 leading-relaxed">
              Lesson audio is generated by the Kokoro-82M open-source TTS engine as a background job.
              To activate: deploy the Kokoro service, set <code className="bg-blue-100 px-1 rounded">KOKORO_API_URL</code> in your environment,
              then toggle the "TTS Audio Generation" feature flag. Existing lessons with
              <code className="bg-blue-100 px-1 rounded">status = 'pending'</code> will queue automatically.
            </p>
            <p className="text-xs text-blue-700 mt-2">
              Admins can also manually upload human narration via the course editor — this bypasses TTS entirely.
            </p>
          </div>
        </div>
      </div>

      {/* Job list */}
      <div className="et-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-border text-left">
                {['Lesson', 'Course', 'Provider', 'Duration', 'Status', 'Generated', ''].map(h => (
                  <th key={h} className="px-4 py-3 text-xs font-bold uppercase tracking-widest text-muted-foreground">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {audioJobs?.map(job => {
                const lesson = job.lessons as { id: string; title: string; courses: { title: string } | null } | null
                return (
                  <tr key={job.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-4 py-3 text-sm font-medium text-navy-500">{lesson?.title || '—'}</td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">{lesson?.courses?.title || '—'}</td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">{providerLabels[job.audio_provider] || job.audio_provider}</td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">
                      {job.duration_seconds ? formatDuration(job.duration_seconds) : '—'}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`badge-pill text-[10px] ${statusColors[job.status] || 'bg-gray-100 text-gray-700'}`}>
                        {job.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">
                      {job.generated_at ? formatRelativeTime(job.generated_at) : '—'}
                    </td>
                    <td className="px-4 py-3">
                      {job.status === 'failed' && (
                        <button className="text-xs font-semibold text-red-600 hover:text-red-700">
                          Retry
                        </button>
                      )}
                      {job.audio_url && (
                        <a href={job.audio_url} target="_blank" rel="noopener noreferrer"
                          className="text-xs font-semibold text-blue-600 hover:text-blue-700">
                          Listen →
                        </a>
                      )}
                    </td>
                  </tr>
                )
              })}
              {(!audioJobs || audioJobs.length === 0) && (
                <tr>
                  <td colSpan={7} className="px-4 py-12 text-center text-sm text-muted-foreground">
                    No audio jobs yet. Generate audio from the course editor or enable the TTS pipeline.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
